tbc/config/routes.rb
Rails.application.routes.draw do

  get 'reservas/crear' => 'reserva#create', :as => 'reserva_cree'
  get 'reserva/' => 'reserva#index'

  resources :vcubs
  put 'vcubs/:id/posicion' => 'vcubs#cambiar_posicion'
  put 'vcubs/:id/estado' => 'vcubs#cambiar_estado'
  put 'vcubs/:id/prestada' => 'vcubs#cambiar_prestada'

  get 'administrador' => 'usuarios#administrador'

  get 'emergencia/' => 'emergencia#index'
  get 'emergencia/create'
  get 'emergencia/show'
  get 'emergencia/destroy'

  resources :tranvia do

    resources :reportets
  end

  put 'tranvia/:id/posicion' => 'tranvia#cambiar_posicion'
  put 'tranvia/:id/estado' => 'tranvia#cambiar_estado'
  post 'tranvia/:id/emergencia' => 'tranvia#emergencia'
  post 'tranvia/:id/reportar' => 'tranvia#reporte'

  get 'reportets/' => 'reportets#index', :as =>'reportet'
  get 'reportets/create'

  get 'reportems/' => 'reportems#index', :as =>'reportem'
  get 'reportems/create'

  
  resources :mobibuses do
    resources :reportems
  end
  put 'mobibuses/:id/posicion'  => 'mobibuses#cambiar_posicion'
  put 'mobibuses/:id/estado'  => 'mobibuses#cambiar_estado'
  post 'mobibuses/:id/reportar' => 'mobibuses#reporte'
  resources :usuarios
  post 'usuarios/:id/reserva' => 'usuarios#reservar'

  resources :conductors

  post 'conductors/:id/asignarm' => 'conductors#asignarm'

  post 'conductors/:id/asignart' => 'conductors#asignart'

  get 'reportets/create' => 'reportets#create', :as => 'reportets_crear'
  get 'reportems/create' => 'reportems#create', :as => 'reportems_crear'

  resources :reportets

  resources :reportems

  root 'usuarios#access'

end

tbc/app/models/conductor.rb
class Conductor < ActiveRecord::Base
end

tbc/app/models/conductormobibus.rb
class Conductormobibus < ActiveRecord::Base
  belongs_to :mobibus
  belongs_to :conductor
end

tbc/app/models/conductortranvia.rb
class Conductortranvia < ActiveRecord::Base
  belongs_to :tranvium
  belongs_to :conductor
end

tbc/app/models/emergencia.rb
class Emergencia < ActiveRecord::Base
end

tbc/app/models/mobibus.rb
class Mobibus < ActiveRecord::Base
  has_many :reportem, dependent: :destroy
end

tbc/app/models/reportem.rb
class Reportem < ActiveRecord::Base
  belongs_to :mobibus
end

tbc/app/models/reportet.rb
class Reportet < ActiveRecord::Base
  belongs_to :tranvium
end

tbc/app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :usuario
end

tbc/app/models/tranvium.rb
class Tranvium < ActiveRecord::Base
end

tbc/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

tbc/app/models/vcub.rb
class Vcub < ActiveRecord::Base
end

tbc/app/helpers/application_helper.rb
module ApplicationHelper
end

tbc/app/helpers/conductors_helper.rb
module ConductorsHelper
end

tbc/app/helpers/emergencia_helper.rb
module EmergenciaHelper
end

tbc/app/helpers/holas_helper.rb
module HolasHelper
end

tbc/app/helpers/mobibuses_helper.rb
module MobibusesHelper
end

tbc/app/helpers/reportems_helper.rb
module ReportemsHelper
end

tbc/app/helpers/reportets_helper.rb
module ReportetsHelper
end

tbc/app/helpers/reserva_helper.rb
module ReservaHelper
end

tbc/app/helpers/tranvia_helper.rb
module TranviaHelper
end

tbc/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

tbc/app/helpers/vcubs_helper.rb
module VcubsHelper
end

tbc/app/views/vcubs/_form.html.erb
<%= form_for(@vcub) do |f| %>
  <% if @vcub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vcub.errors.count, "error") %> prohibited this vcub from being saved:</h2>

      <ul>
      <% @vcub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :posicion %><br>
    <%= f.text_field :posicion %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :prestada %><br>
    <%= f.check_box :prestada %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tbc/app/views/vcubs/edit.html.erb
<h1>Editing vcub</h1>

<%= render 'form' %>

<%= link_to 'Show', @vcub %> |
<%= link_to 'Back', vcubs_path %>

tbc/app/views/vcubs/index.html.erb
<h1>Listing vcubs</h1>

<table>
  <thead>
    <tr>
      <th>Posicion</th>
      <th>Estado</th>
      <th>Prestada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vcubs.each do |vcub| %>
      <tr>
        <td><%= vcub.posicion %></td>
        <td><%= vcub.estado %></td>
        <td><%= vcub.prestada %></td>
        <td><%= link_to 'Show', vcub %></td>
        <td><%= link_to 'Edit', edit_vcub_path(vcub) %></td>
        <td><%= link_to 'Destroy', vcub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vcub', new_vcub_path %>

tbc/app/views/vcubs/new.html.erb
<h1>New vcub</h1>

<%= render 'form' %>

<%= link_to 'Back', vcubs_path %>

tbc/app/views/vcubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Posicion:</strong>
  <%= @vcub.posicion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @vcub.estado %>
</p>

<p>
  <strong>Prestada:</strong>
  <%= @vcub.prestada %>
</p>

<%= link_to 'Edit', edit_vcub_path(@vcub) %> |
<%= link_to 'Back', vcubs_path %>