tbc/config/routes.rb
Rails.application.routes.draw do

  get 'reservas/crear' => 'reserva#create', :as => 'reserva_cree'
  get 'reserva/' => 'reserva#index'

  resources :vcubs
  put 'vcubs/:id/posicion' => 'vcubs#cambiar_posicion'
  put 'vcubs/:id/estado' => 'vcubs#cambiar_estado'
  put 'vcubs/:id/prestada' => 'vcubs#cambiar_prestada'

  get 'administrador' => 'usuarios#administrador'

  get 'emergencia/' => 'emergencia#index'
  get 'emergencia/create'
  get 'emergencia/show'
  get 'emergencia/destroy'

  resources :tranvia do

    resources :reportets
  end

  put 'tranvia/:id/posicion' => 'tranvia#cambiar_posicion'
  put 'tranvia/:id/estado' => 'tranvia#cambiar_estado'
  post 'tranvia/:id/emergencia' => 'tranvia#emergencia'
  post 'tranvia/:id/reportar' => 'tranvia#reporte'

  get 'reportets/' => 'reportets#index', :as =>'reportet'
  get 'reportets/create'

  get 'reportems/' => 'reportems#index', :as =>'reportem'
  get 'reportems/create'

  
  resources :mobibuses do
    resources :reportems
  end
  put 'mobibuses/:id/posicion'  => 'mobibuses#cambiar_posicion'
  put 'mobibuses/:id/estado'  => 'mobibuses#cambiar_estado'
  post 'mobibuses/:id/reportar' => 'mobibuses#reporte'
  resources :usuarios
  post 'usuarios/:id/reserva' => 'usuarios#reservar'

  resources :conductors

  post 'conductors/:id/asignarm' => 'conductors#asignarm'

  post 'conductors/:id/asignart' => 'conductors#asignart'

  get 'reportets/create' => 'reportets#create', :as => 'reportets_crear'
  get 'reportems/create' => 'reportems#create', :as => 'reportems_crear'

  resources :reportets

  resources :reportems

  root 'usuarios#access'

end

tbc/app/models/conductor.rb
class Conductor < ActiveRecord::Base
end

tbc/app/models/conductormobibus.rb
class Conductormobibus < ActiveRecord::Base
  belongs_to :mobibus
  belongs_to :conductor
end

tbc/app/models/conductortranvia.rb
class Conductortranvia < ActiveRecord::Base
  belongs_to :tranvium
  belongs_to :conductor
end

tbc/app/models/emergencia.rb
class Emergencia < ActiveRecord::Base
end

tbc/app/models/mobibus.rb
class Mobibus < ActiveRecord::Base
  has_many :reportem, dependent: :destroy
end

tbc/app/models/reportem.rb
class Reportem < ActiveRecord::Base
  belongs_to :mobibus
end

tbc/app/models/reportet.rb
class Reportet < ActiveRecord::Base
  belongs_to :tranvium
end

tbc/app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :usuario
end

tbc/app/models/tranvium.rb
class Tranvium < ActiveRecord::Base
end

tbc/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

tbc/app/models/vcub.rb
class Vcub < ActiveRecord::Base
end

tbc/app/controllers/conductors_controller.rb
class ConductorsController < ApplicationController
  before_action :set_conductor, only: [:show, :edit, :update, :destroy, :asignarm, :asignart]

  # GET /conductors
  # GET /conductors.json
  def index
    @conductors = Conductor.all
    render :json => @conductors
  end

  # GET /conductors/1
  # GET /conductors/1.json
  def show
  end

  # GET /conductors/new
  def new
    @conductor = Conductor.new
  end

  # GET /conductors/1/edit
  def edit
  end

  # POST /conductors
  # POST /conductors.json
  def create
    @conductor = Conductor.new(conductor_params)

    respond_to do |format|
      if @conductor.save
        format.html { redirect_to @conductor, notice: 'Conductor was successfully created.' }
        format.json { render :show, status: :created, location: @conductor }
      else
        format.html { render :new }
        format.json { render json: @conductor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conductors/1
  # PATCH/PUT /conductors/1.json
  def update
    respond_to do |format|
      if @conductor.update(conductor_params)
        format.html { redirect_to @conductor, notice: 'Conductor was successfully updated.' }
        format.json { render :show, status: :ok, location: @conductor }
      else
        format.html { render :edit }
        format.json { render json: @conductor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conductors/1
  # DELETE /conductors/1.json
  def destroy
    @conductor.destroy
    respond_to do |format|
      format.html { redirect_to conductors_url, notice: 'Conductor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /conductors/1
  # POST /conductors/1.json
  def asignarm
    idmobi = params[:idMobibus]
    id =  @conductor.id
    @conductormobibus = Conductormobibus.new
    @conductormobibus.update_attributes(mobibus_id: idmobi, conductor_id: id)
    @conductormobibus.save
    @conductormobibuses = Conductormobibus.all
  end

  def asignart
    idtranvi = params[:idTranvia]
    id =  @conductor.id
    @conductortranvia = Conductortranvia.new
    @conductortranvia.update_attributes(tranvium_id: idtranvi, conductor_id: id)
    @conductortranvia.save
    @conductortranvia = Conductortranvia.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conductor
      @conductor = Conductor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conductor_params
      params.require(:conductor).permit(:nombre, :cedula)
    end
end

tbc/app/helpers/application_helper.rb
module ApplicationHelper
end

tbc/app/helpers/conductors_helper.rb
module ConductorsHelper
end

tbc/app/helpers/emergencia_helper.rb
module EmergenciaHelper
end

tbc/app/helpers/holas_helper.rb
module HolasHelper
end

tbc/app/helpers/mobibuses_helper.rb
module MobibusesHelper
end

tbc/app/helpers/reportems_helper.rb
module ReportemsHelper
end

tbc/app/helpers/reportets_helper.rb
module ReportetsHelper
end

tbc/app/helpers/reserva_helper.rb
module ReservaHelper
end

tbc/app/helpers/tranvia_helper.rb
module TranviaHelper
end

tbc/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

tbc/app/helpers/vcubs_helper.rb
module VcubsHelper
end

tbc/app/views/conductors/_form.html.erb
<%= form_for(@conductor) do |f| %>
  <% if @conductor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conductor.errors.count, "error") %> prohibited this conductor from being saved:</h2>

      <ul>
      <% @conductor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.number_field :cedula %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
Prueba de commit

tbc/app/views/conductors/asignarm.html.erb
<h1>Listado Conductor-Mobibus</h1>
<% @mobibus_id%>
<% @id%>
<table>
  <thead>
  <tr>
    <th>Conductor</th>
    <th>Mobibus</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @conductormobibuses.each do |conductorm| %>
      <tr>
        <td><%= conductorm.conductor_id %></td>
        <td><%= conductorm.mobibus_id%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

tbc/app/views/conductors/asignart.html.erb
<h1>Listado Conductor-Tranvia</h1>
<% @tranvia_id%>
<% @id%>
<table>
  <thead>
  <tr>
    <th>Conductor</th>
    <th>Tranvia</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @conductortranvia.each do |conductort| %>
      <tr>
        <td><%= conductort.conductor_id %></td>
        <td><%= conductort.tranvium_id%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

tbc/app/views/conductors/edit.html.erb
<h1>Editing conductor</h1>

<%= render 'form' %>

<%= link_to 'Show', @conductor %> |
<%= link_to 'Back', conductors_path %>

tbc/app/views/conductors/index.html.erb
<h1>Listing conductors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cedula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conductors.each do |conductor| %>
      <tr>
        <td><%= conductor.nombre %></td>
        <td><%= conductor.cedula %></td>
        <td><%= link_to 'Show', conductor %></td>
        <td><%= link_to 'Edit', edit_conductor_path(conductor) %></td>
        <td><%= link_to 'Destroy', conductor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conductor', new_conductor_path %>

tbc/app/views/conductors/new.html.erb
<h1>New conductor</h1>

<%= render 'form' %>

<%= link_to 'Back', conductors_path %>

tbc/app/views/conductors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @conductor.nombre %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @conductor.cedula %>
</p>

<%= link_to 'Edit', edit_conductor_path(@conductor) %> |
<%= link_to 'Back', conductors_path %>