tbc/config/routes.rb
Rails.application.routes.draw do

  get 'reservas/crear' => 'reserva#create', :as => 'reserva_cree'
  get 'reserva/' => 'reserva#index'

  resources :vcubs
  put 'vcubs/:id/posicion' => 'vcubs#cambiar_posicion'
  put 'vcubs/:id/estado' => 'vcubs#cambiar_estado'
  put 'vcubs/:id/prestada' => 'vcubs#cambiar_prestada'

  get 'administrador' => 'usuarios#administrador'

  get 'emergencia/' => 'emergencia#index'
  get 'emergencia/create'
  get 'emergencia/show'
  get 'emergencia/destroy'

  resources :tranvia do

    resources :reportets
  end

  put 'tranvia/:id/posicion' => 'tranvia#cambiar_posicion'
  put 'tranvia/:id/estado' => 'tranvia#cambiar_estado'
  post 'tranvia/:id/emergencia' => 'tranvia#emergencia'
  post 'tranvia/:id/reportar' => 'tranvia#reporte'

  get 'reportets/' => 'reportets#index', :as =>'reportet'
  get 'reportets/create'

  get 'reportems/' => 'reportems#index', :as =>'reportem'
  get 'reportems/create'

  
  resources :mobibuses do
    resources :reportems
  end
  put 'mobibuses/:id/posicion'  => 'mobibuses#cambiar_posicion'
  put 'mobibuses/:id/estado'  => 'mobibuses#cambiar_estado'
  post 'mobibuses/:id/reportar' => 'mobibuses#reporte'
  resources :usuarios
  post 'usuarios/:id/reserva' => 'usuarios#reservar'

  resources :conductors

  post 'conductors/:id/asignarm' => 'conductors#asignarm'

  post 'conductors/:id/asignart' => 'conductors#asignart'

  get 'reportets/create' => 'reportets#create', :as => 'reportets_crear'
  get 'reportems/create' => 'reportems#create', :as => 'reportems_crear'

  resources :reportets

  resources :reportems

  root 'usuarios#access'

end

tbc/app/models/conductor.rb
class Conductor < ActiveRecord::Base
end

tbc/app/models/conductormobibus.rb
class Conductormobibus < ActiveRecord::Base
  belongs_to :mobibus
  belongs_to :conductor
end

tbc/app/models/conductortranvia.rb
class Conductortranvia < ActiveRecord::Base
  belongs_to :tranvium
  belongs_to :conductor
end

tbc/app/models/emergencia.rb
class Emergencia < ActiveRecord::Base
end

tbc/app/models/mobibus.rb
class Mobibus < ActiveRecord::Base
  has_many :reportem, dependent: :destroy
end

tbc/app/models/reportem.rb
class Reportem < ActiveRecord::Base
  belongs_to :mobibus
end

tbc/app/models/reportet.rb
class Reportet < ActiveRecord::Base
  belongs_to :tranvium
end

tbc/app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :usuario
end

tbc/app/models/tranvium.rb
class Tranvium < ActiveRecord::Base
end

tbc/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

tbc/app/models/vcub.rb
class Vcub < ActiveRecord::Base
end

tbc/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario,  only: [:show, :edit, :update, :destroy,:reservar]
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
    render :json => @usuarios
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  def access
  end

  def administrador
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    @vacio = "jiop"
    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /usuarios/1/reservar
  # POST /usuarios/.json
  def reservar
    @id = @usuario.id
    laRuta= params["ruta"]
    direccionL= params["direccionLlegada"]
    direccionO= params["direccionOrigen"]
    tiempo = Time.now
    horaS = tiempo.hour
    horaL = horaS+6
    redirect_to(reserva_cree_path( estado: "nuevo",fecha: tiempo, direccion_llegada: direccionO, direccion_salida: direccionL, horaSalida: horaS, horaLlegada: horaL, ruta: laRuta, distancia: 0, idUsuario: @id, nombreUsuario: @usuario.nombre))
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :documento, :correo, :contrasenia)
    end

end

tbc/app/helpers/application_helper.rb
module ApplicationHelper
end

tbc/app/helpers/conductors_helper.rb
module ConductorsHelper
end

tbc/app/helpers/emergencia_helper.rb
module EmergenciaHelper
end

tbc/app/helpers/holas_helper.rb
module HolasHelper
end

tbc/app/helpers/mobibuses_helper.rb
module MobibusesHelper
end

tbc/app/helpers/reportems_helper.rb
module ReportemsHelper
end

tbc/app/helpers/reportets_helper.rb
module ReportetsHelper
end

tbc/app/helpers/reserva_helper.rb
module ReservaHelper
end

tbc/app/helpers/tranvia_helper.rb
module TranviaHelper
end

tbc/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

tbc/app/helpers/vcubs_helper.rb
module VcubsHelper
end

tbc/app/views/usuarios/_form.html.erb
# encoding: utf-8
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :nombre, :placeholder => "Nombre", class: "form-control" %>
  </div>
  <div>
    <%= f.text_field :documento, :placeholder => "Documento", class: "form-control" %>
  </div>
  <div>
    <%= f.text_field :correo, :placeholder => "Correo",class: "form-control" %>
  </div>
  <div>
    <%= f.password_field :contrasenia, :placeholder => "Contraseña",class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :value=> "Regístrate!",class: "btn btn-success form-control" %>
  </div>
<% end %>

tbc/app/views/usuarios/access.erb
# encoding: utf-8
<div class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0;background:white">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#inicio">
        <i class='fa fa-rocket'></i>
        TBC
      </a>
    </div>
    <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav'>
        <li>
          <a href="#inicio">Nosotros</a>
        </li>
        <li>
          <a href='#nosotros'>Servicios</a>
        </li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Correo" style="width:120px">
        </div>
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Contraseña" style="width:120px">
        </div>
        <button type="submit" class="btn btn-info">Ingresar</button>
      </form>
    </div>
  </div>
</div>
<div class="container-fluid" style="padding:20px;background:#6699ff;color:white;margin-top:50px;">
  <div class="row">
    <div class="col-md-3 col-md-offset-2 text-center">
      <br>
      <i class="fa fa-fighter-jet fa-5x" style="color:white"></i>
    </div>
    <div class="col-md-5 text-center">
      <h1>
        Bienvenido a TBC
      </h1>
      <p>
        TBC es una empresa de transporte público de la ciudad comprometida con el medio ambiente. Actualmente contamos con 250 tranvías, 250 mobibus y 4000 vcubs para prestar el mejor servicio posible a los usuarios
      </p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row col-md-12 text-center" style="margin-bottom:50px">
    <h1>Nuestros servicios:</h1>
  </div>
  <div class="row">
    <div class="col-md-4 text-center">
      <i class="fa fa-cab fa-5x"></i><br>
      <h1>Mobibus</h1>
      <p class="text-justify">
        Nuestro servicio de mobibus Está diseñado para personas con necesidades especiales. Reserva con anticipación un carro para que te lleve a donde necesites
      </p>
    </div>
    <div class="col-md-4 text-center">
      <i class="fa fa-train fa-5x"></i><br>
      <h1>Tranvía</h1>
      <p class="text-justify">
        Nuestro servicio de tranvía cuenta actualmente con tres lineas que recorren la ciudad y están activas desde las 5 A.M. hasta la media noche.
      </p>
    </div>
    <div class="col-md-4 text-center">
      <i class="fa fa-bicycle fa-5x"></i><br>
      <h1>Vcub</h1>
      <p class="text-justify">
        Nuestro servicio de vcubs es nuestro servicio ecológico. Alquila una bicicleta en cualquiera de las estaciones habilitadas y devuélvela en cualquier otra.
      </p>
    </div>
  </div>
</div>
<div class="container-fluid" style="background:#6699ff;color:white;padding-top:50px;margin-bottom:20px">
  <div class="container col-md-8 col-md-offset-2">
    <div class="row text-center">
      <h1>¡Comienza a usar nuestros servicios ahora!</h1>
    </div>
    <div class="row col-md-offset-2" style='margin-bottom:50px;padding-top:20px'>
      <div class="col-md-4">
        <p>
          Únete a más de 5000 usuarios satisfechos que usan nuestros medios de transporte
        </p>
      </div>
      <div class='col-md-4'>
        <%= @usuario= Usuario.new
            render 'form' %>
      </div>
    </div>
  </div>
</div>
<div class="text-right" style="font-size:8px">
  <a href="administrador">Ingreso de administrador</a>
</div>

tbc/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

tbc/app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Documento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.documento %></td>
        <td><%= usuario.id %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

tbc/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

tbc/app/views/usuarios/show.html.erb
# encoding: utf-8
<div class="navbar navbar-default navbar-fixed-top" style="margin-bottom:0;background:white">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#inicio">
        <i class='fa fa-rocket'></i>
        TBC
      </a>
    </div>
    <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav'>
        <li>
          <a href="#inicio"><%= @usuario.nombre %></a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#">Salir</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="container-fluid" style="margin-top:50px;">
  <div class="col-md-5 col-md-offset-3 text-center" style="padding-top:50px;">
    <i class="fa fa-frown-o fa-5x"></i>
    <h2>No tienes actividad aún. Solicita un servicio</h2>
    <div class="modal fade" id="reservar" tabindex="-1" role="dialog" aria-labelledby="tituloreservar" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
            <h4 class="modal-title" id="tituloreservar">Reservar mobibus</h4>
          </div>
          <div class="modal-body">
            <form class="text-left">
              <div class="form-group">
                <label for="fechaservicio">¿Cuándo necesitas el servicio?</label>
                <input id="fechaservicio" type="date" class="form-control" placeholder="Fecha de tu reserva">
              </div>
              <div class="form-group">
                <label for="direccionsalida">¿Dónde deberíamos recogerte?</label>
                <input id="direccionsalida" type="text" class="form-control" placeholder="Dirección de salida">
              </div>
              <div class="form-group">
                <label for="direccionllegada">¿A dónde necesitas ir?</label>
                <input id="direccionllegada" type="text" class="form-control" placeholder="Dirección de destino">
              </div>
              <div class="form-group">
                <label for="horasalida">¿A qué hora debemos llegar por ti?</label>
                <input id="horasalida" type="time" class="form-control" placeholder="Hora de salida">
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-primary">Confirmar</button>
          </div>
        </div>
      </div>
    </div>
    <br>
    <button class="btn btn-default" data-toggle="modal" data-target="#reservar">Reserva un mobibus</button>
    <button class="btn btn-default">Alquila un vcub</button>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <h1>Tu información</h1>
    <div class="text-right" style="font-size:8pt;">
      <%= link_to 'Editar', edit_usuario_path(@usuario) %>
    </div>
    <p>
      <%= @usuario.nombre %>
    </p>
    <p>
      Documento: <%= @usuario.documento %>
    </p>
    <p>
      <%= @usuario.correo %>
    </p>
  </div>
</div>