tbc/config/routes.rb
Rails.application.routes.draw do

  get 'reservas/crear' => 'reserva#create', :as => 'reserva_cree'
  get 'reserva/' => 'reserva#index'

  resources :vcubs
  put 'vcubs/:id/posicion' => 'vcubs#cambiar_posicion'
  put 'vcubs/:id/estado' => 'vcubs#cambiar_estado'
  put 'vcubs/:id/prestada' => 'vcubs#cambiar_prestada'

  get 'administrador' => 'usuarios#administrador'

  get 'emergencia/' => 'emergencia#index'
  get 'emergencia/create'
  get 'emergencia/show'
  get 'emergencia/destroy'

  resources :tranvia do

    resources :reportets
  end

  put 'tranvia/:id/posicion' => 'tranvia#cambiar_posicion'
  put 'tranvia/:id/estado' => 'tranvia#cambiar_estado'
  post 'tranvia/:id/emergencia' => 'tranvia#emergencia'
  post 'tranvia/:id/reportar' => 'tranvia#reporte'

  get 'reportets/' => 'reportets#index', :as =>'reportet'
  get 'reportets/create'

  get 'reportems/' => 'reportems#index', :as =>'reportem'
  get 'reportems/create'

  
  resources :mobibuses do
    resources :reportems
  end
  put 'mobibuses/:id/posicion'  => 'mobibuses#cambiar_posicion'
  put 'mobibuses/:id/estado'  => 'mobibuses#cambiar_estado'
  post 'mobibuses/:id/reportar' => 'mobibuses#reporte'
  resources :usuarios
  post 'usuarios/:id/reserva' => 'usuarios#reservar'

  resources :conductors

  post 'conductors/:id/asignarm' => 'conductors#asignarm'

  post 'conductors/:id/asignart' => 'conductors#asignart'

  get 'reportets/create' => 'reportets#create', :as => 'reportets_crear'
  get 'reportems/create' => 'reportems#create', :as => 'reportems_crear'

  resources :reportets

  resources :reportems

  root 'usuarios#access'

end

tbc/app/models/conductor.rb
class Conductor < ActiveRecord::Base
end

tbc/app/models/conductormobibus.rb
class Conductormobibus < ActiveRecord::Base
  belongs_to :mobibus
  belongs_to :conductor
end

tbc/app/models/conductortranvia.rb
class Conductortranvia < ActiveRecord::Base
  belongs_to :tranvium
  belongs_to :conductor
end

tbc/app/models/emergencia.rb
class Emergencia < ActiveRecord::Base
end

tbc/app/models/mobibus.rb
class Mobibus < ActiveRecord::Base
  has_many :reportem, dependent: :destroy
end

tbc/app/models/reportem.rb
class Reportem < ActiveRecord::Base
  belongs_to :mobibus
end

tbc/app/models/reportet.rb
class Reportet < ActiveRecord::Base
  belongs_to :tranvium
end

tbc/app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :usuario
end

tbc/app/models/tranvium.rb
class Tranvium < ActiveRecord::Base
end

tbc/app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

tbc/app/models/vcub.rb
class Vcub < ActiveRecord::Base
end

tbc/app/controllers/reportems_controller.rb
class ReportemsController < ApplicationController
  before_action :set_reportem, only: [:show]

  def index
    @reportems = Reportem.all
    render :json => @reportems
  end

  def new
    @reportem = Reportem.new
  end

  def create
    @reportem = Reportem.new
    @reportem.update_attributes(mobibus_id: params[:idMobibus], fecha: params[:fecha], trayectos: params[:trayectos])
    @reportem.save
    redirect_to reportem_path
  end

  def show
  end

  def destroy
  end

  private

  def set_reportem
    @reportem = Reportem.find(params[:id])
  end
end

tbc/app/helpers/application_helper.rb
module ApplicationHelper
end

tbc/app/helpers/conductors_helper.rb
module ConductorsHelper
end

tbc/app/helpers/emergencia_helper.rb
module EmergenciaHelper
end

tbc/app/helpers/holas_helper.rb
module HolasHelper
end

tbc/app/helpers/mobibuses_helper.rb
module MobibusesHelper
end

tbc/app/helpers/reportems_helper.rb
module ReportemsHelper
end

tbc/app/helpers/reportets_helper.rb
module ReportetsHelper
end

tbc/app/helpers/reserva_helper.rb
module ReservaHelper
end

tbc/app/helpers/tranvia_helper.rb
module TranviaHelper
end

tbc/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

tbc/app/helpers/vcubs_helper.rb
module VcubsHelper
end

tbc/app/views/reportems/_form.html.erb
<%= form_for(@reportem) do |f| %>
  <% if @reportem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reportem.errors.count, "error") %> prohibited this reportem from being saved:</h2>

      <ul>
      <% @reportem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :trayectos %><br>
    <%= f.number_field :trayectos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tbc/app/views/reportems/edit.html.erb
<h1>Editing reportem</h1>

<%= render 'form' %>

<%= link_to 'Show', @reportem %> |
<%= link_to 'Back', reportems_path %>

tbc/app/views/reportems/index.html.erb
<h1>Listing reportems</h1>

<table>
  <thead>
    <tr>
      <th>IDMobibus</th>
      <th>Fecha</th>
      <th>Trayectos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reportems.each do |reportem| %>
      <tr>
        <td><%= reportem.mobibus_id %></td>
        <td><%= reportem.fecha %></td>
        <td><%= reportem.trayectos %></td>
        <td><%= link_to 'Show', reportem %></td>
        <td><%= link_to 'Edit', edit_reportem_path(reportem) %></td>
        <td><%= link_to 'Destroy', reportem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reportem', new_reportem_path %>

tbc/app/views/reportems/new.html.erb
<h1>New reportem</h1>

<%= render 'form' %>

<%= link_to 'Back', reportems_path %>

tbc/app/views/reportems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @reportem.fecha %>
</p>

<p>
  <strong>Trayectos:</strong>
  <%= @reportem.trayectos %>
</p>

<%= link_to 'Edit', edit_reportem_path(@reportem) %> |
<%= link_to 'Back', reportems_path %>